name: Release
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build -v .
      
      


name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
      id: go
    - name: Build
      run: ./dist.sh
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
