name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
      id: go
    - name: Build
      run: ./dist.sh
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
